name: Deploy Server to EC2

on:
  push:
    branches: [master]
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update and deploy
        run: |
          cd ~/chatsee/server
          git fetch origin
          git rebase origin/master
          yarn
          pm2 restart chatsee-server || pm2 start app.js --name "chatsee-server" --watch
          pm2 save
